In [16]:
import numpy as np
a = np.array([0,1,2,3,4])
c = np.array([[1,2,3,4],[5,6,7,8]])
c.shape

(2, 4)

In [17]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:7:2])


[2 4 6]


In [27]:
b = np.arange(30,70,2)
b

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [44]:
c = np.arange(15,55)
print(c[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [3]:
import numpy as np
x = np.array([0,11,14,34,56,45])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[ 0 11 14 34 56 45]
Test if none of the elements of the said array is zero:
False


In [4]:
import numpy as np
X=np.array([0,11,14,34,56,45])
x = np.where(X==0)
print(x)

(array([0], dtype=int64),)


In [10]:
import numpy as np
x = np.array([10,11,12,13,14,15,16,17,18,19,20,21])
print(x.reshape(3,4))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [12]:
import numpy as np
x = np.array([12,34,56,57,30,43])
print(x.dtype)

int32


In [7]:
def younger(c1,c2,c3):
    if(c1<c2 and c1<c3):
        print("c1 is younger")
        
    elif(c2<c1 and c2<c3):
        print("c2 is younger")
        
    elif(c3<c1 and c3<c2):
        print("c3 is younger")
    
younger(c1=2,c2=5,c3=6)

c1 is younger


In [15]:
import cmath

a = 2 + 3j
b = 5 + 4j

print(a+b)
print(a.real)
print(a.imag)


(7+7j)
2.0
3.0


In [17]:
import cmath
 
# Initializing complex number
z = 5+3j
# Print the parts of Complex No.
print("The real part of complex number is : ", end="")
print(z.real)
 
print("The imaginary part of complex number is : ", end="")
print(z.imag)

The real part of complex number is : 5.0
The imaginary part of complex number is : 3.0


In [21]:
import numpy as np

z = np.array([10,20,30,40,50,60,70,80,90])
print(z[1:7:2])

[20 40 60]


In [31]:
import numpy as np

a = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a.reshape(2,4))

[[10 20 30 40]
 [50 60 70 80]]


In [33]:
import numpy as np 
a = np.array([10,20,30,40])
c = a.copy()
v = a.view()
a[0] = 42
print(a)
print(c)
print("This is array of view:",v)

[42 20 30 40]
[10 20 30 40]
This is array of view: [42 20 30 40]


In [45]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [55]:
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6]], [[7 ,8, 9],[10, 11, 12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [59]:
a = [10,7,2,8,3,2]
a.sort()
print(a)

[2, 2, 3, 7, 8, 10]


In [8]:
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
b =np.array([[1,1,1],[1,1,1],[1,1,1]])
c = np.sum((a,b),axis = 1)
d = np.sum((a,b),axis = 0)
print("a=",end = '')
print(a)
print("\n")

print("b=",end = '')
print(b)
print("\n")

print("sumc=",end = '')
print(c)
print("\n")

print("sumr=",end = '')
print(d)


a=[[10 20 30]
 [40 50 60]
 [70 80 90]]


b=[[1 1 1]
 [1 1 1]
 [1 1 1]]


sumc=[[120 150 180]
 [  3   3   3]]


sumr=[[11 21 31]
 [41 51 61]
 [71 81 91]]


In [68]:
import numpy as np
a = np.array([[10,20,30],[40,50,60]])
b = np.array([[4,5,6],[1,2,3]])
c = np.concatenate((a,b),axis=1)
print(c)

[[10 20 30  4  5  6]
 [40 50 60  1  2  3]]


In [24]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dstack((a,b))
e = np.stack((a,b))
print(c)
print(e)

[[[1 4]
  [2 5]
  [3 6]]]
[[1 2 3]
 [4 5 6]]


In [74]:
import numpy as np
a = np.array([10,7,2,8,3])
d = np.where(a%2==0)
print(d)

(array([0, 2, 3], dtype=int64),)


In [1]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90,100])
filter_arr = []

n = int(input("Enter the filter:"))

for x in arr:
    if x>n:
        filter_arr.append(True)
    else:
         filter_arr.append(False)

new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False, True, True, True, True, True, True, True, True, True]
[ 20  30  40  50  60  70  80  90 100]


In [79]:
import numpy as np

arr = np.array(["vishal","ankush","bat"])
c = np.sort(arr)
print(c)

['ankush' 'bat' 'vishal']


In [84]:
import numpy as np
arr = []
for x in range(10):
    n = int(input("Enter the no:"))
    arr.append(n)
    arr.sort()
    
print(arr)

[1, 2, 3, 6, 7, 8, 9, 10, 14, 15]


In [10]:
import numpy as np 
a = np.array([1,2,3,4])
np.sum(a)
a.mean()                     #mean
np.median(a)                 #median
a.std()                      #Standard deviation
a.max()

4

In [15]:
import numpy as np
data = np.loadtxt('dataa.txt')
data
year, hares, lynxes, carrots = data.T #columns to variables
print(year)
print(hares)
print(data)
data.std(axis=1)
np.argmax(data,axis=1)



[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]
[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]
[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


array([3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 1, 1, 2, 3, 3, 3, 3, 3],
      dtype=int64)

In [7]:
'''
Find the shape, transpose of given array.
a = [[21,31,41], [51,61,71]]
'''

import numpy as np
a = np.array([[21,31,41], [51,61,71]])
print(a)
print(a.shape)
print(a.T)


[[21 31 41]
 [51 61 71]]
(2, 3)
[[21 51]
 [31 61]
 [41 71]]


In [8]:
'''
Perform Flattening on the following array.
a = [[88,99,66], [33, 55, 22]]
'''
import numpy as np
a = np.array([[88,99,66], [33, 55, 22]])
c = a.ravel()
print(c)

[88 99 66 33 55 22]


In [10]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)


    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [5]:
import pandas as pd
df = pd.read_csv('are.csv')
df.head()


City  Edition      Sport       Discipline               Athlete  \
29211  Beijing     2008  Wrestling  Wrestling Gre-R        ENGLICH, Mirko   
29212  Beijing     2008  Wrestling  Wrestling Gre-R  MIZGAITIS, Mindaugas   
29213  Beijing     2008  Wrestling  Wrestling Gre-R       PATRIKEEV, Yuri   
29214  Beijing     2008  Wrestling  Wrestling Gre-R         LOPEZ, Mijain   
29215  Beijing     2008  Wrestling  Wrestling Gre-R        BAROEV, Khasan   

       NOC Gender       Event Event_gender   Medal  
29211  GER    Men   84 - 96kg            M  Silver  
29212  LTU    Men  96 - 120kg            M  Bronze  
29213  ARM    Men  96 - 120kg            M  Bronze  
29214  CUB    Men  96 - 120kg            M    Gold  
29215  RUS    Men  96 - 120kg            M  Silver

In [13]:
import pandas as pd
df = pd.read_csv('are.csv')
df.tail()


City  Edition      Sport       Discipline               Athlete  \
29211  Beijing     2008  Wrestling  Wrestling Gre-R        ENGLICH, Mirko   
29212  Beijing     2008  Wrestling  Wrestling Gre-R  MIZGAITIS, Mindaugas   
29213  Beijing     2008  Wrestling  Wrestling Gre-R       PATRIKEEV, Yuri   
29214  Beijing     2008  Wrestling  Wrestling Gre-R         LOPEZ, Mijain   
29215  Beijing     2008  Wrestling  Wrestling Gre-R        BAROEV, Khasan   

       NOC Gender       Event Event_gender   Medal  
29211  GER    Men   84 - 96kg            M  Silver  
29212  LTU    Men  96 - 120kg            M  Bronze  
29213  ARM    Men  96 - 120kg            M  Bronze  
29214  CUB    Men  96 - 120kg            M    Gold  
29215  RUS    Men  96 - 120kg            M  Silver

In [8]:
import pandas as pd
df = pd.read_csv('are.csv')
df.sample(10)


City  Edition       Sport       Discipline  \
2212     Stockholm     1912     Fencing          Fencing   
22373      Atlanta     1996  Gymnastics      Artistic G.   
6178   Los Angeles     1932      Rowing           Rowing   
17659  Los Angeles     1984      Rowing           Rowing   
25153       Sydney     2000   Wrestling  Wrestling Gre-R   
25797       Athens     2004    Baseball         Baseball   
27429      Beijing     2008    Aquatics  Synchronized S.   
10841        Tokyo     1964   Athletics        Athletics   
13706       Munich     1972     Sailing          Sailing   
19183        Seoul     1988      Rowing           Rowing   

                         Athlete  NOC Gender                     Event  \
2212   MONTGOMERIE, Robert Cecil  GBR    Men                 épée team   
22373           TUGURLAN, Mirela  ROU  Women          team competition   
6178            BARBIERI, Renato  ITA    Men  eight with coxswain (8+)   
17659   CLIMENT HUERTA, Fernando  ESP    Men         coxless pair (2-)   
25153               SIM, Kwon-Ho  KOR    Men                 48 - 54kg   
25797                OUGH, Wayne  AUS    Men                  baseball   
27429         KHASYANOVA, Elvira  RUS  Women                      team   
10841   MATTHEWS, Kenneth Joseph  GBR    Men                 20km walk   
13706       DEAN, Peter Sweetser  USA    Men                   tempest   
19183                RABE, Bahne  FRG    Men  eight with coxswain (8+)   

      Event_gender   Medal  
2212             M  Silver  
22373            W  Bronze  
6178             M  Silver  
17659            M  Silver  
25153            M    Gold  
25797            M  Silver  
27429            W    Gold  
10841            M    Gold  
13706            X  Bronze  
19183            M    Gold

In [17]:
import pandas as pd
df = pd.read_csv('are.csv')
df[['City','Medal']]


City   Medal
0       Athens    Gold
1       Athens  Silver
2       Athens  Bronze
3       Athens    Gold
4       Athens  Silver
...        ...     ...
29211  Beijing  Silver
29212  Beijing  Bronze
29213  Beijing  Bronze
29214  Beijing    Gold
29215  Beijing  Silver

[29216 rows x 2 columns]

In [19]:
import pandas as pd
df = pd.read_csv('are.csv')
df.City


0         Athens
1         Athens
2         Athens
3         Athens
4         Athens
          ...   
29211    Beijing
29212    Beijing
29213    Beijing
29214    Beijing
29215    Beijing
Name: City, Length: 29216, dtype: object

In [8]:
import pandas as pd
pd.options.display.max_rows=70
df = pd.read_csv('are.csv')
df.head(10)


City  Edition     Sport Discipline                Athlete  NOC Gender  \
0  Athens     1896  Aquatics   Swimming          HAJOS, Alfred  HUN    Men   
1  Athens     1896  Aquatics   Swimming       HERSCHMANN, Otto  AUT    Men   
2  Athens     1896  Aquatics   Swimming      DRIVAS, Dimitrios  GRE    Men   
3  Athens     1896  Aquatics   Swimming     MALOKINIS, Ioannis  GRE    Men   
4  Athens     1896  Aquatics   Swimming     CHASAPIS, Spiridon  GRE    Men   
5  Athens     1896  Aquatics   Swimming  CHOROPHAS, Efstathios  GRE    Men   
6  Athens     1896  Aquatics   Swimming          HAJOS, Alfred  HUN    Men   
7  Athens     1896  Aquatics   Swimming       ANDREOU, Joannis  GRE    Men   
8  Athens     1896  Aquatics   Swimming  CHOROPHAS, Efstathios  GRE    Men   
9  Athens     1896  Aquatics   Swimming          NEUMANN, Paul  AUT    Men   

                        Event Event_gender   Medal  
0              100m freestyle            M    Gold  
1              100m freestyle            M  Silver  
2  100m freestyle for sailors            M  Bronze  
3  100m freestyle for sailors            M    Gold  
4  100m freestyle for sailors            M  Silver  
5             1200m freestyle            M  Bronze  
6             1200m freestyle            M    Gold  
7             1200m freestyle            M  Silver  
8              400m freestyle            M  Bronze  
9              400m freestyle            M    Gold

In [3]:
import pandas as pd
df = pd.read_csv('are.csv')
df['Medal']


NameError: name 'Gold' is not defined

In [4]:
import pandas as pd
df = pd.read_csv('v.csv')
print(df.shape)
df
print(pd.options.display.max_rows)


(5, 4)
60


In [11]:
import pandas as pd
df = pd.read_csv('v.csv')
print(df.shape)
print(df)
df.describe()

(5, 4)
  FirstName  LastName  RollNo Branch
0    Vishal  Sonawane      61      A
1    Tushar      Aher      51      B
2    Devesh   Turakne      12      A
3     Swami     Patil       6      A
4    Arjun     Shejul       2      B


RollNo
count   5.000000
mean   26.400000
std    27.482722
min     2.000000
25%     6.000000
50%    12.000000
75%    51.000000
max    61.000000

In [14]:
import pandas as pd
df = pd.read_csv('are.csv')
df.to_csv('new.csv')

In [23]:
'''
1) Read the following dataset father_son.csv .
perform the following operations:
i) print first 5 records, last 5 records
ii) select father column from dataframe
ii)find the shape of dataframe and display statistic
information of dataframe
'''
import pandas as pd 
df = pd.read_csv('father_son.csv')
df.Father
df.describe()

Father          Son
count  1078.000000  1078.000000
mean     67.686827    68.684230
std       2.745827     2.816194
min      59.000000    58.500000
25%      65.800000    66.900000
50%      67.800000    68.600000
75%      69.600000    70.500000
max      75.400000    78.400000

In [30]:
'''
1) Read the following dataset balloons_dataset.csv and perform following operations:
i) Print head, tail,
ii)Print all columns
iii)Split data into feature and target variables of given balloons dataset and print feature and target
variable.
'''

#i) Print head, tail,
import pandas as pd
df = pd.read_csv('balloons_dataset.csv')
df.head()
df.tail()



color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  ADULT        T
3   YELLOW  SMALL  STRETCH  ADULT        T
4   YELLOW  SMALL  STRETCH  ADULT        T
..     ...    ...      ...    ...      ...
95  PURPLE  LARGE      DIP  CHILD        F
96  PURPLE  LARGE      DIP  CHILD        F
97  PURPLE  LARGE      DIP  CHILD        F
98  PURPLE  LARGE      DIP  CHILD        F
99  PURPLE  LARGE      DIP  CHILD        F

[100 rows x 5 columns]

In [33]:
#iii)Split data into feature and target variables of given balloons dataset and print feature and target
#variable
import pandas as pd
df = pd.read_csv('balloons_dataset.csv')
X = df.drop('inflated',axis = 1)
y = df['inflated']
X.head()
y.tail()

95    F
96    F
97    F
98    F
99    F
Name: inflated, dtype: object

In [34]:
#ii)Print all columns
import pandas as pd
df = pd.read_csv('balloons_dataset.csv')
X = df.drop('inflated',axis = 1)
y = df['inflated']
df.columns


Index(['color', 'size', 'act', 'age', 'inflated'], dtype='object')

In [47]:
import pandas as pd
df = pd.read_excel('weather_data.xlsx')
df

day      city  temperature  windspeed   event
0  2017-01-01  new york           32          6    Rain
1  2017-02-01  new york           36          7   Sunny
2  2017-03-01  new york           28         12    Snow
3  2017-04-01  new york           33          7   Sunny
4  2017-01-01    mumbai           90          5   Sunny
5  2017-02-01    mumbai           85         12     Fog
6  2017-03-01    mumbai           87         15     Fog
7  2017-04-01    mumbai           92          5    Rain
8  2017-01-01     paris           45         20   Sunny
9  2017-02-01     paris           50         13  Cloudy
10 2017-03-01     paris           54          8  Cloudy
11 2017-04-01     paris           42         10  Cloudy

In [54]:
import pandas as pd
df.to_csv('new.csv')
df.to_csv('new_noIndex.csv',index=False)
df.to_excel('new.xlsx',sheet_name='weather_data')

In [2]:
import pandas as pd 
url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
df = pd.read_csv(url)
df

Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [2]:
import pandas as pd 
df = pd.read_excel('weather_data.xlsx')
df.to_csv('weather_data.csv')
df


day      city  temperature  windspeed   event
0  2017-01-01  new york           32          6    Rain
1  2017-02-01  new york           36          7   Sunny
2  2017-03-01  new york           28         12    Snow
3  2017-04-01  new york           33          7   Sunny
4  2017-01-01    mumbai           90          5   Sunny
5  2017-02-01    mumbai           85         12     Fog
6  2017-03-01    mumbai           87         15     Fog
7  2017-04-01    mumbai           92          5    Rain
8  2017-01-01     paris           45         20   Sunny
9  2017-02-01     paris           50         13  Cloudy
10 2017-03-01     paris           54          8  Cloudy
11 2017-04-01     paris           42         10  Cloudy

In [22]:
import pandas as pd 
df = pd.read_csv('weather_data.csv')
g = df.groupby('city')
g.get_group('new york')
#print(g.max())
#print(g.mean)
print(g.describe())

         Unnamed: 0                                             temperature  \
              count mean       std  min   25%  50%    75%   max       count   
city                                                                          
mumbai          4.0  5.5  1.290994  4.0  4.75  5.5   6.25   7.0         4.0   
new york        4.0  1.5  1.290994  0.0  0.75  1.5   2.25   3.0         4.0   
paris           4.0  9.5  1.290994  8.0  8.75  9.5  10.25  11.0         4.0   

                 ...              windspeed                                    \
           mean  ...    75%   max     count   mean       std  min   25%   50%   
city             ...                                                            
mumbai    88.50  ...  90.50  92.0       4.0   9.25  5.057997  5.0  5.00   8.5   
new york  32.25  ...  33.75  36.0       4.0   8.00  2.708013  6.0  6.75   7.0   
paris     47.75  ...  51.00  54.0       4.0  12.75  5.251984  8.0  9.50  11.5   

                       
            75

In [15]:
import pandas as pd 
df = pd.read_csv('weather_data.csv')
h = df.groupby('day')
h.get_group('2017-02-01')

Unnamed: 0         day      city  temperature  windspeed   event
1           1  2017-02-01  new york           36          7   Sunny
5           5  2017-02-01    mumbai           85         12     Fog
9           9  2017-02-01     paris           50         13  Cloudy

In [23]:
import pandas as pd 

exam_data = pd.DataFrame({
    'name':['Anastasia','Dima','Katherine','James','Emily','Michael','Matthew','Laura','Kevin','Jonas'],
    'score': [12.5, 9, 16.5, 18, 9, 20, 14.5, 11, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes','no','yes','no','no','yes','yes','no','no','yes']
})
exam_data

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James   18.0         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura   11.0         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [6]:
'''
Perform loc and iloc operations on the given dataframe
a= ([3,6,16,32,18,36,19,38,8,16,5,10])
i) loc[8] ,
ii) df.iloc[:2]
iii) loc[:5] ,
iv) loc[45]
'''

import pandas as pd
a= pd.DataFrame([3,6,16,32,18,36,19,38,8,16,5,10])
print(a)
print("\n")
print(a.loc[8])
print("\n")
print(a.iloc[:2])
print("\n")
print(a.loc[:5])
print("\n")
#print(a.loc[45])

     0
0    3
1    6
2   16
3   32
4   18
5   36
6   19
7   38
8    8
9   16
10   5
11  10


0    8
Name: 8, dtype: int64


   0
0  3
1  6


    0
0   3
1   6
2  16
3  32
4  18
5  36


